image: php:8.2

definitions:
  caches:
    composer: ~/.composer/cache

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip git
              - curl -sS https://getcomposer.org/installer | php
              - php composer.phar install --no-interaction --prefer-dist
              - ./vendor/bin/phpunit || true

        - step:
            name: Lint
            script:
              - find . -name '*.php' -exec php -l {} \;

  branches:
    dev:
      - step:
          name: Deploy DEV
          script:
            - echo "Deploy DEV"
            - curl -s "https://ploi.io/webhooks/servers/105108/sites/338203/deploy?token=6TLih2A7cNCps8pRT5GDqZ0DaXe7KGsy35vNHBc669956J6pCl&direct=true"

    production:
      - step:
          name: Deploy PROD
          script:
            - echo "Deploy PROD"
            - curl -s "https://ploi.io/webhooks/servers/87653/sites/277546/deploy?token=wKyxh2b5CuWpcEcGeahGkmGpfQP9KXiR769rDipSS9JMY50wik&direct=true"